version: '2'
services:
  elasticsearch:
    hostname: elastic
    domainname: elk-local
    image: elasticsearch:5.6.9
    ports:
      - "9200"
      - "9300"
    volumes:
      - "./data:/data"
  kibana:
    hostname: kibana
    domainname: elk-local
    image: kibana
    ports:
      - "81:5601"
  logstash:
    hostname: logstash
    domainname: elk-local
    command: logstash -e 'input { stdin {  } http { port => 8080 } } output { elasticsearch { hosts => [ 'elasticsearch' ] index => "elk-data-%{+YYYY.MM.dd}" } stdout { } }'
    image: logstash
    ports:
      - "8089:8080"
volumes:
  data:
    driver: local