version: "3"

services:

  service-composer:
    build:
      context: .
      dockerfile: Dockerfile
    image: service-composer
    environment:
      - SOLUTIONBUILDER_WORKINGDIRECTORY=/service-composer
      - SOLUTIONBUILDER_LOADBALANCERADDRESS=192.168.99.100
      - SOLUTIONBUILDER_NUMBEROFBUILDTORETAIN=10
    ports:
      - "7070:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/local/bin/docker:/usr/local/bin/docker"
      - "/composer-repo:/mvn-repo"
    deploy:
      placement:
        constraints: [node.role == manager]
