apiVersion: v1
data:
  mongodb: stpmongo:WHvoRJpptwHudYKbOQDiGHXAvNEVRbfFgJ8gppvqcc4QjOYsPyaj3v71JS9GtfZAPdiuObR64Z9KzSiecdQgbA==@stpmongo.documents.azure.com:10255/STPlatform?ssl=true
  test123:  this is test123  
  stploadbanlance: 52.168.161.236 
  acceleratorwkdir: /service-composer
  buildsToRetain: "10" 
  
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T19:14:38Z
  name: stpconfig
  namespace: default
  