version: '2'

services:
 my_shiny:
  image: stpregistry.azurecr.io/stp-cognitivemarketplace-ui:4.2
  ports:
  - 80:80
  volumes:
  - /c/Users/Jaseel.Haris/Desktop/Shiny/logs/:/var/log/shiny-server

 my_sentiment:
  image: stpregistry.azurecr.io/stp-cognitivemarketplace-algo1:1.0
  ports:
  - 8080:8080

 my_claim:
  image: stpregistry.azurecr.io/stp-cognitivemarketplace-algo2:1.0
  ports:
  - 8081:8081
 
 my_influencer:
  image: stpregistry.azurecr.io/stp-cognitivemarketplace-algo3:1.0
  ports:
  - 8082:8082

 my_topic:
  image: stpregistry.azurecr.io/stp-cognitivemarketplace-algo4:1.0
  ports:
  - 8086:8086
  
 my_lead:
  image: stpregistry.azurecr.io/stp-cognitivemarketplace-algo5:1.0
  ports:
  - 8085:8085

 my_psycho:
  image: stpregistry.azurecr.io/stp-cognitivemarketplace-algo6:1.0
  ports:
  - 8083:8083

 my_email:
  image: stpregistry.azurecr.io/stp-cognitivemarketplace-algo7:1.0
  ports:
  - 8084:8084

 my_lstm:
  image: stpregistry.azurecr.io/stp-cognitivemarketplace-algo8:1.0
  ports:
  - 8087:8087

 my_sentiup:
  image: stpregistry.azurecr.io/stp-cognitivemarketplace-algo1-up:1.0
  ports:
  - 8088:8088

 my_topicup:
  image: stpregistry.azurecr.io/stp-cognitivemarketplace-algo4-up:1.0
  ports:
  - 8089:8089
 
 
 
 

