apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testmsaccelarator
spec:
  template:
    metadata:
      labels:
        app: testmsaccelarator
        component: ui
    spec:    
      containers:
      - name: testmsaccelarator
        image: stpregistry.azurecr.io/stp-msaccelarator:22.0        
        imagePullPolicy: Always
        ports:
        - containerPort: 8080        
        env:        
        - name: SOLUTIONBUILDER_WORKINGDIRECTORY
          valueFrom:
            configMapKeyRef:
              name: stpconfig
              key: acceleratorwkdir  
        - name: SOLUTIONBUILDER_NUMBEROFBUILDTORETAIN
          valueFrom:
            configMapKeyRef:
              name: stpconfig
              key: buildsToRetain 
      
       
    