apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stp-mstf
spec:
  template:
    metadata:
      labels:
        app: stp-mstf
        component: ui
    spec:
      containers:
      - name: stp-mstf
        image: stpregistry.azurecr.io/stp-mstf:3.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          