apiVersion: v1
kind: Service
metadata:
  labels:
    app: stp-platform-ui
    component: ui
  name: stp-platform-ui
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080  
    nodePort: 32357
  selector:
    app: stp-platform-ui
    component: ui
    
    