apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: x2cdemo
spec:
  template:
    metadata:
      labels:
        app: x2cdemo
        component: ui
    spec:
      containers:
      - name: x2cdemo
        image: stpregistry.azurecr.io/x2cdemo:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          