apiVersion: v1
kind: Service
metadata:
  labels:
    app: stp-mstf
    component: ui
  name: stp-mstf
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: stp-mstf
    component: ui
    
    