apiVersion: v1
kind: Service
metadata:
  labels:
    app: stp-cognitivemkplace
    component: ui
  name: stp-cognitivemkplace
spec:
  type: NodePort
  ports:
  - port: 80   
    nodePort: 32352
  selector:
    app: stp-cognitivemkplace
    component: ui
    
    