apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stp-platform-ui
spec:
  template:
    metadata:
      labels:
        app: stp-platform-ui
        component: ui
    spec:
      containers:
      - name: stp-platform-ui
        image: stpregistry.azurecr.io/stp-platform-ui:6.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          