apiVersion: v1
kind: Service
metadata:
  labels:
    app: stp-platform-service
    component: ui
  name: stp-platform-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32355
  selector:
    app: stp-platform-service
    component: ui
    
    