version: "3"

services:
  #<block-portainer-start>
  
  portainer:
    image: portainer/portainer
    ports:
      - "7000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
#      - "/opt/portainer:/data"
    deploy:
      placement:
        constraints: [node.role == manager]
  #<block-portainer-end>
  #<block-docker-visualizer-start>
  
  visualizer:
    image: dockersamples/visualizer
    ports:
      - "7001:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
  #<block-docker-visualizer-end>