version: "3"

services:

  portainer:
    image: portainer/portainer
    ports:
      - "7000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
#      - "/opt/portainer:/data"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - monitoringnet

#  dvizz:
#    image: visualization/dvizz
#    ports:
#      - "7001:6969"
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock"
#    deploy:
#      placement:
#        constraints: [node.role == manager]
#    networks:
#      - monitoringnet

#  visualizer:
#    image: dockersamples/visualizer
#    ports:
#      - "8888:8080"
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock"
#    deploy:
#      placement:
#        constraints: [node.role == manager]
#    networks:
#      - microservicesnet
      
networks:
  monitoringnet:
    driver: overlay
   