server:
  port: 80
  contextPath: /
  
spring:
  application:
    name: edge-service-zuul
    
ribbon:
  eureka:
    enabled: false
    
#<block-zuul-routes-start>    
zuul:
  routes:
    #<block-oauth2-authorization-service-start>
    authService:
      path: /auth-service/**
      url: http://localhost:8000/auth-service/
      sensitiveHeaders:
    #<block-oauth2-authorization-service-end>
    #<block-resource-service-template-start>
    demoService:
      path: /demo-service/**
      url: http://localhost:8090/demo-service/
      sensitiveHeaders:
    #<block-resource-service-template-end>
    #<block-client-application-java-start>
    clientApplication:
      path: /client-app-java/**
      url: http://localhost:8080/client-app-java/
      sensitiveHeaders:
    #<block-client-application-java-end>
    #<block-client-application-angular4-start>
    clientApplicationSpa:
      path: /client-app-angular4/**
      url: http://localhost:4200/
      sensitiveHeaders:
    #<block-client-application-angular4-end>
    #<block-micro-frontends-start>
    microFrontendApp:
      path: /micro-frontends/**
      url: http://localhost:4201/
      sensitiveHeaders:
    #<block-micro-frontends-end>
    #<block-zipkin-server-start>
    #<block-oauth2-authorization-service-start>
    zipkinAuth:
      path: /zipkin-auth/**
      url: http://localhost:9411/
      sensitiveHeaders:
    #<block-oauth2-authorization-service-end>
    zipkinServer:
      path: /zipkin/**
      url: http://localhost:9411/zipkin/
      sensitiveHeaders:
    #<block-zipkin-server-end>
    #<block-eureka-server-start>
    eurekaServer:
      path: /eureka/**
      url: http://localhost:8761/eureka/
      sensitiveHeaders:
    #<block-eureka-server-end>
    
#<block-zuul-routes-end>
      
edgeService:
  uri: 
  port: 
      
302RedirectUrls:
  settings:
    dummy: /
    #<block-oauth2-authorization-service-start>
    auth-service: /auth-service
    #<block-oauth2-authorization-service-end>
    #<block-client-application-java-start>
    client-app-java: /client-app-java
    #<block-client-application-java-end>
    #<block-zipkin-server-start>
    zipkin: /zipkin
    #<block-zipkin-server-end>
    #<block-eureka-server-start>
    eureka: /eureka
    #<block-eureka-server-end>

#<block-default-home-page-start>
homePage: /
#<block-default-home-page-end>
#<block-client-application-java-start>    
homePage: /client-app-java
#<block-client-application-java-end>
#<block-client-application-angular4-start>    
homePage: /client-app-angular4
#<block-client-application-angular4-end>
#<block-micro-frontends-home-start>    
homePage: /micro-frontends
#<block-micro-frontends-home-end>