---
- hosts: all
  remote_user: ec2-user
  become: yes
  become_method: sudo
  tasks:
  - name: curl install
    yum: name=curl state=present
  - name: Docker install
    yum: name=docker state=present
  - name: install docker-py
   Pip: name=docker-py
  - name: Start and Enable Docker
    service: name=docker state=started enabled=yes
  - name: Run the container
    docker:
      name: Mywebapp
      image: nagaramesh/ywebapp
      state: reloaded
     pull: always
      ports:
      - "8080:8080"
