server:
  port: 5050
  contextPath: /service-composer
  
spring:
  application:
    name: service-composer
    
solutionBuilder:
  workingDirectory: /service-composer-wd	
  sourceFile: /config/source/java-source.zip
  numberOfBuildsToRetain: 10
  loadBalancerAddress: 192.168.99.100