server:
  port: 8080
  contextPath: /client-app-java
  
spring:
  application:
    name: client-app-java
    
  thymeleaf:
    prefix: classpath:/templates

#<block-non-oauth2-authorization-service-start>
security:
  basic:
    enabled: false
#<block-non-oauth2-authorization-service-end>

#<block-oauth2-authorization-service-start>   
security:
  oauth2:
    client:
      clientId: demo-client-app
      clientSecret: secret
      use-current-uri: false
      #<block-non-edge-service-zuul-start>
      accessTokenUri: http://localhost:8000/auth-service/oauth/token
      userAuthorizationUri: http://localhost:8000/auth-service/oauth/authorize
      tokenInvalidateUri: http://localhost:8000/auth-service/user/invalidateToken
      pre-established-redirect-uri: http://localhost:8080/client-app-java/login
      registered-redirect-uri: http://localhost:8080/client-app-java/login
      #<block-non-edge-service-zuul-end>
      #<block-edge-service-zuul-start>
      accessTokenUri: http://localhost/auth-service/oauth/token
      userAuthorizationUri: http://localhost/auth-service/oauth/authorize
      tokenInvalidateUri: http://localhost/auth-service/user/invalidateToken
      pre-established-redirect-uri: http://localhost/client-app-java/login
      registered-redirect-uri: http://localhost/client-app-java/login
      #<block-edge-service-zuul-end>
    resource:
      #<block-non-edge-service-zuul-start>
      userInfoUri: http://localhost:8000/auth-service/user/me
      #<block-non-edge-service-zuul-end>
      #<block-edge-service-zuul-start>
      userInfoUri: http://localhost/auth-service/user/me
      #<block-edge-service-zuul-end>
#<block-oauth2-authorization-service-end> 

dependentServices:
  #<block-resource-service-template-start>
  #<block-non-edge-service-zuul-start>
  demoServiceUri: http://localhost:8090/demo-service
  #<block-non-edge-service-zuul-end>
  #<block-edge-service-zuul-start>
  demoServiceUri: http://localhost/demo-service
  #<block-edge-service-zuul-end>
  #<block-resource-service-template-end>

  #<block-micro-frontends-start>
  #<block-non-edge-service-zuul-start>
  microFrontendAppUri: http://localhost:4201/#/dashboard
  #<block-non-edge-service-zuul-end>
  #<block-edge-service-zuul-start>
  microFrontendAppUri: http://localhost/micro-frontends/#/dashboard
  #<block-edge-service-zuul-end>
  #<block-micro-frontends-end>